name: docker

on: [push]
  # workflow_run:
  #   workflows: [testUnitaire]

  #   types: [completed]  

env:
  TEST_TAG_devops: modestin/devops:test
  LATEST_TAG_devops: modestin/devops:latest
  TEST_TAG_mysql: modestin/mysql:test
  LATEST_TAG_mysql: modestin/mysql:latest
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: connexion docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export devops to Docker
        uses: docker/build-push-action@v6
        with:
          contexte: ./db
          load: true
          tags: ${{ env.TEST_TAG_devops }}

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG_devops }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: windows/amd64,windows/arm64
          push: true
          tags: ${{ env.LATEST_TAG_devops }}
      - name: Build and export mysql to Docker
        uses: docker/build-push-action@v6
        with:
          contexte: .
          load: true
          tags: ${{ env.TEST_TAG_mysql }}

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG_mysql }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: windows/amd64,windows/arm64
          push: true
          tags: ${{ env.LATEST_TAG_devops_mysql }}