name: testUnitaire

on: [push]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: installation PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring
          coverage: none

      - name: installation dependa,ces 
        run: composer install

      - name: permission accordée
        run: chmod +x ./vendor/bin/phpunit
      - name: Run test
        run: ./vendor/bin/phpunit --configuration phpunit.xml
      - name: afficher success
        run: echo "termine et reussie"
